[unstable]
build-std-features = ["compiler-builtins-mem"] # provides feautres for memory related operations
build-std = ["core", "compiler_builtins", "alloc"]
bindeps = true

[build]
target="kernel-target.json"

[target.'cfg(target_os = "none")']
runner = "bootimage runner"